<?php
function set_rn_options(){
	add_option('rn_bgcolor','FFFFFF','','no');
	add_option('rn_useImage','true','','no');
	add_option('rn_txtStyle','2','','no');
	add_option('rn_txtAlign','left','','no');
	add_option('rn_txtColor','E7580D','','no');
	add_option('rn_txtSize','12','','no');
	add_option('rn_paddingTop','5','','no');
	add_option('rn_paddingRight','20','','no');
	add_option('rn_paddingBottom','5','','no');
	add_option('rn_paddingLeft','60','','no');
	add_option('rn_useBorderTop','true','','no');
	add_option('rn_useBorderRight','false','','no');
	add_option('rn_useBorderBottom','true','','no');
	add_option('rn_useBorderLeft','false','','no');
	add_option('rn_borderSize','2','','no');
	add_option('rn_borderColor','666666','','no');
	add_option('rn_borderStyle','solid','','no');
	add_option('rn_button','small','','no');
	add_option('rn_new','true','','no');
	add_option('rn_new_msg','You\'re new! If you like it here, please subscribe to my feed.','','no');
	add_option('rn_new_icon','rss.png','','no');
	add_option('rn_digg','true','','no');
	add_option('rn_digg_msg','Welcome <strong>Digg</strong> user! If you like this article, please consider a digg.','','no');
	add_option('rn_digg_button','true','','no');
	add_option('rn_reddit','true','','no');
	add_option('rn_reddit_msg','Welcome <strong>Reddit</strong> user! If you like this article, please give me some points.','','no');
	add_option('rn_reddit_button','true','','no');
	add_option('rn_delicious','true','','no');
	add_option('rn_delicious_msg','Welcome <strong>del.icio.us</strong> user! Don\'t forget to save this page to your bookmarks.','','no');
	add_option('rn_facebook','true','','no');
	add_option('rn_facebook_msg','Welcome <strong>Facebook</strong> user!','','no');
	add_option('rn_slashdot','true','','no');
	add_option('rn_slashdot_msg','Welcome <strong>Slashdot</strong> user!','','no');
	add_option('rn_technorati','true','','no');
	add_option('rn_technorati_msg','Welcome <strong>Technorati</strong> user!','','no');
	add_option('rn_stumbleupon','true','','no');
	add_option('rn_stumbleupon_msg','Welcome <strong>StumbleUpon</strong> user! If you like this article, simply give it a thumbs up.','','no');
	add_option('rn_fark','true','','no');
	add_option('rn_fark_msg','Welcome <strong>Fark</strong> user!','','no');
	add_option('rn_newsvine','true','','no');
	add_option('rn_newsvine_msg','Welcome <strong>Newsvine</strong> user!','','no');
	add_option('rn_blinklist','true','','no');
	add_option('rn_blinklist_msg','Welcome <strong>Blinklist</strong> user!','','no');
	add_option('rn_propeller','true','','no');
	add_option('rn_propeller_msg','Welcome <strong>Propeller</strong> user!','','no');
	add_option('rn_mybloglog','true','','no');
	add_option('rn_mybloglog_msg','Welcome <strong>MyBlogLog</strong> user!','','no');
	add_option('rn_magnolia','true','','no');
	add_option('rn_magnolia_msg','Welcome <strong>Ma.gnolia</strong> user!','','no');
	add_option('rn_squidoo','true','','no');
	add_option('rn_squidoo_msg','Welcome <strong>Squidoo</strong> user!','','no');
	add_option('rn_blogmarks','true','','no');
	add_option('rn_blogmarks_msg','Welcome <strong>Blogmarks</strong> user!','','no');
	add_option('rn_simpy','true','','no');
	add_option('rn_simpy_msg','Welcome <strong>Simpy</strong> user!','','no');
	add_option('rn_shoutwire','true','','no');
	add_option('rn_shoutwire_msg','Welcome <strong>Shoutwire</strong> user!','','no');
	add_option('rn_tailrank','true','','no');
	add_option('rn_tailrank_msg','Welcome <strong>Tailrank</strong> user!','','no');
	add_option('rn_dzone','true','','no');
	add_option('rn_dzone_msg','Welcome <strong>DZone</strong> user!','','no');
	add_option('rn_furl','true','','no');
	add_option('rn_furl_msg','Welcome <strong>Furl</strong> user!','','no');
	add_option('rn_sphinn','true','','no');
	add_option('rn_sphinn_msg','Welcome <strong>Sphinn</strong> user! Please sphinn this article.','','no');
	add_option('rn_sphinn_button','true','','no');
	add_option('rn_designfloat','true','','no');
	add_option('rn_designfloat_msg','Welcome <strong>Designfloat</strong> user! Don\'t forget to float this article if you like it.','','no');
	add_option('rn_designfloat_button','true','','no');
	add_option('rn_google','true','','no');
	add_option('rn_google_msg','Welcome <strong>Google</strong> user! Did you find what you were looking for? Have a nice stay.','','no');
	add_option('rn_live','true','','no');
	add_option('rn_live_msg','Welcome <strong>Live</strong> user! Did you find what you were looking for? Have a nice stay.','','no');
	add_option('rn_yahoo','true','','no');
	add_option('rn_yahoo_msg','Welcome <strong>Yahoo</strong> user! Did you find what you were looking for? Have a nice stay.','','no');
	add_option('rn_custom1','true','','no');
	add_option('rn_custom1_url','truemediaconcepts.com','','no');
	add_option('rn_custom1_msg','Welcome True Media Concepts user!','','no');
	add_option('rn_custom1_icon','#.png','','no');
	add_option('rn_custom2','true','','no');
	add_option('rn_custom2_url','feedburner.com','','no');
	add_option('rn_custom2_msg','Welcome back RSS feed reader! I\'m sure you\'ll like this new article.','','no');
	add_option('rn_custom2_icon','rss.png','','no');
	add_option('rn_custom3','false','','no');
	add_option('rn_custom3_url','','','no');
	add_option('rn_custom3_msg','','','no');
	add_option('rn_custom3_icon','','','no');
	add_option('rn_custom4','false','','no');
	add_option('rn_custom4_url','','','no');
	add_option('rn_custom4_msg','','','no');
	add_option('rn_custom4_icon','','','no');
	add_option('rn_custom5','false','','no');
	add_option('rn_custom5_url','','','no');
	add_option('rn_custom5_msg','','','no');
	add_option('rn_custom5_icon','','','no');
	add_option('rn_blogrush','true','','no');
	add_option('rn_blogrush_msg','Welcome <strong>BlogRush</strong> user! Feel free to subscribe to my RSS feed if you liked this article.','','no');
	add_option('rn_testmode','no','','no');
	add_option('rn_testmode_timer', time());
}
?>
